### ISSUE TITLE
GetInt does not return max on recover

### ISSUE THREAD

**Issue by Skarlso** [mazen160/go-random#1]
Hi!

Well done for your first project. :) Keep it up and welcome to the community!

Here is your first issue. :D

https://github.com/mazen160/go-random/blob/master/random.go#L25

This is needlessly convoluted. :) Int only panics if your in is below 0. So just add a case for that in the being and return an error like, can't define max as below 0.

Other then that, the recursive `i` call makes no sense. If there is a panic, it will just continue and n will not be 0. If n IS zero, which is unlikely to happen, it will always be zero because you didn't actually change `i` you called it with the same parameter. In which case, if you just call it again with the same again it should produce the same 0 value. Maybe you intended to call it with a different value?

And what does this mean? 
>// If fails, it returns the max int and an error.
Max of what? Max of `int` as a value in Go? Because it doesn't do that right now.

Cheers! Good luck! :)

**Comment by mazen160** [comment]
Hi @Skarlso 
Thank you very much for the warm welcome and for reviewing the project! 

It's funny I was blocked on this bug and probably didn't enough coffee that day :) Reading your comment and re-reading the docs now makes much more sense. I just fixed it now on https://github.com/mazen160/go-random/commit/5e14a6f3a23315de8127d5d8bbcb5df9462790e6

Thank you very much again!

**Comment by Skarlso** [comment]
Awesome! :) You're Welcome. :)
